services:
  app:
    build:
      args:
        user: loteria
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: loteria
    container_name: loteria_app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - loteria_network
  db:
    image: mysql:8.0
    container_name: loteria_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - loteria_volume:/var/lib/mysql
    networks:
      - loteria_network
  nginx:
    image: nginx:alpine
    container_name: loteria_nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - loteria_network

networks:
  loteria_network:
    driver: bridge

volumes:
  loteria_volume: